name: tagGame
main: de.Brogamer5000.tagGame.tagGame
version: 1.0
commands:
   taggame:
      description: Tag - Du bist!
      usage: Syntax error! Bitte nutze /taggame help
permissions:
   taggame.reset:
      default: false
   taggame.forceset:
      default: false
